## Coupling interfaces have code flow that is dependent on orientation of the interface.
## This test is to check the code flow for horizontal acoustic-elastic interface with acoustic domain on top.

parameters:

  header:
    ## Header information is used for logging. It is good practice to give your simulations explicit names
    title: Homogeneous anisotropic crystal
    # A detailed description for your simulation
    description: |
      Material systems : Elastic Anisotropic domain
      Interfaces : None
      Sources : Force source (1)
      Boundary conditions : Neumann BCs on all edges

  simulation-setup:
    ## quadrature setup
    quadrature:
      quadrature-type: GLL4

    ## Solver setup
    solver:
      time-marching:
        type-of-simulation: forward
        time-scheme:
          type: Newmark
          dt: 55.e-9
          nstep: 1500

    simulation-mode:
      forward:
        writer:
          seismogram:
            format: ascii
            directory: "./OUTPUT_FILES/results"

          display:
            format: PNG
            directory: ./OUTPUT_FILES/results
            field: displacement
            simulation-field: forward
            time-interval: 100

  receivers:
    stations: "./OUTPUT_FILES/STATIONS"
    angle: 0.0
    seismogram-type:
      - displacement
    nstep_between_samples: 1

  ## Runtime setup
  run-setup:
    number-of-processors: 1
    number-of-runs: 1

  ## databases
  databases:
    mesh-database: "./OUTPUT_FILES/database.bin"

  ## Sources
  sources: "./source.yaml"
